branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - "changelogFile": "CHANGELOG.md"
  - - "@semantic-release/git"
    - assets: ["CHANGELOG.md"]
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - - "@semantic-release/github"
    - assets:
        - path: dist/resume-light.pdf
          label: Resume(Light)
        - path: dist/resume-dark.pdf
          label: Resume(Dark)
