name: LaTex To PDF

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Compile LaTex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RESUME
          path: resume.pdf

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: resume.pdf
